# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'

    # Emplacement des pdfs
    pdf_directory: '%kernel.project_dir%/public/FAUXDGS/'

    # Emplacement des entitys
    entity_directory: 'App\Entity\'

    # Emplacement des entitys
    form_directory: 'App\Form\'

    # Ids des enums (identifient des lignes spécifiques de la DB)
    id_etat_brouillon: '1'
    id_etat_valide: '2'
    id_typeAction_brouillon: '1'
    id_typeAction_ajout: '2'
    id_typeAction_suppression: '3'
    id_typeAction_modification: '4'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\AdminHelper:
        arguments:
            $entityDirectory: '%entity_directory%'
            $formDirectory: '%form_directory%'

    App\Service\GestionnaireActeHelper:
        arguments:
            $pdfDirectory: '%pdf_directory%'